### ISSUE TITLE
webpack issues

### ISSUE THREAD

**Issue by jaredwy** [mattgodbolt/compiler-explorer#609]
The branch for webpack can be found at jw/webpack

Please comment with any issues you find, I will consolidate them into a todo list on this issue.

## TODO

- [x] Look into vis view error 
- [x] Remove all references of bower
- [x] setup webpack dev server

**Comment by mattgodbolt** [comment]
Thank you *so* much! This is fantastic! Taking a look now and as suggested will add comments here (and/or for trivial stuff, fix in-place if you don't mind)

**Comment by mattgodbolt** [comment]
So! I installed yarn and fiddled with the makefile to make it [a] find yarn and [b] use the right version of node with yarn (more on that another time).

I tried `make`:

```
matthew@danger ~/d/compiler-explorer (jw/webpack)> make
Haskell language support disabled
D language support disabled
Rust language support disabled
yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 48.33s.
node node_modules/webpack/bin/webpack.js 

ERROR in ./static/cppp-mode.js
Module not found: Error: Can't resolve 'vs/basic-languages/src/cpp' in '/home/matthew/dev/compiler-explorer/static'
 @ ./static/cppp-mode.js 4:10-47
 @ ./static/editor.js
 @ ./static/hub.js
 @ ./static/main.js

ERROR in ./static/ispc-mode.js
Module not found: Error: Can't resolve 'vs/basic-languages/src/cpp' in '/home/matthew/dev/compiler-explorer/static'
 @ ./static/ispc-mode.js 4:10-47
 @ ./static/editor.js
 @ ./static/hub.js
 @ ./static/main.js
Makefile:61: recipe for target 'webpack' failed
make: *** [webpack] Error 2
```

Any ideas? :)

**Comment by mattgodbolt** [comment]
If it's a clue I noticed the `vs` directory seems to be in the wrong place:

```
$ ls
app.build.js  CODE_OF_CONDUCT.md  c-preload/  examples/  LICENSE        package.json  rust/    views/             yarn.lock
app.js*       CODEOWNERS          d/          haskell/   Makefile       README.md     static/  vs/
bower.json    CONTRIBUTING.md     etc/        lib/       node_modules/  Roadmap.md    test/    webpack.config.js
$ git status
[my WIP changes removed]
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vs/

```

**Comment by mattgodbolt** [comment]
If I move the `vs` directory into the `node_modules` it "worked" ... Maybe the `CopyWebpackPlugin` needs a `to` of `__dirname, "node_modules/vs"` ?

**Comment by mattgodbolt** [comment]
Ok, if I manually move the `vs` directory, and then `make` I get a 404 for `loader.js`

![image](https://user-images.githubusercontent.com/633973/32407591-6970985c-c159-11e7-88a7-1f79b0721610.png)

**Comment by jaredwy** [comment]
Yup. That looks right. I knew there would be one thing missed!

**Comment by mattgodbolt** [comment]
Sweet, will make the changes. You chill, this is super lovely :)

**Comment by jaredwy** [comment]
Change already pushed :)

**Comment by mattgodbolt** [comment]
I don't see the fix, can you double-check you pushed?

**Comment by RabsRincon** [comment]
https://github.com/jaredwy/compiler-explorer/commit/617471b8f52433861a5ebcbf05fee63d167bb252 as far as I can tell

**Comment by mattgodbolt** [comment]
Oh yes, d'oh I forgot it was in a forked repo and not a branch of CE itself. Cheers!

**Comment by mattgodbolt** [comment]
@jaredwy unless I'm missing something we can kill `bower` now, right?

**Comment by mattgodbolt** [comment]
Ok, just pulled and have the bower changes and the changes to put things in `static/vs` but still:

```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 22.25s.
node node_modules/webpack/bin/webpack.js 

ERROR in ./static/cppp-mode.js
Module not found: Error: Can't resolve 'vs/basic-languages/src/cpp' in '/home/matthew/dev/compiler-explorer/static'
 @ ./static/cppp-mode.js 4:10-47
 @ ./static/editor.js
 @ ./static/hub.js
 @ ./static/main.js

ERROR in ./static/ispc-mode.js
Module not found: Error: Can't resolve 'vs/basic-languages/src/cpp' in '/home/matthew/dev/compiler-explorer/static'
 @ ./static/ispc-mode.js 4:10-47
 @ ./static/editor.js
 @ ./static/hub.js
 @ ./static/main.js

matthew@danger ~/d/compiler-explorer (jw/webpack)> ls static/vs
base/  basic-languages/  editor/  language/  loader.js
```

However, running `make` again fixes the issue...

Is there now an ordering thing within the webpack config?

It's 100% reproducible with `make clean; make`

Will take a look (and also add `static/vs` to `.gitignore`)

**Comment by jaredwy** [comment]
🚫 means I havent tested
✅  means tested and good
❌  means tested and something busted

| Feature  |Status|
| ------------- | ------------- |
| C++ Compiling |   ✅|
| Adding new compilers |    ✅ |
| Update to editor updates all compilers|  ✅  |
| Update to editor 2  updates relevant compiler|  ✅  |
| Filters|  ✅  |
| Demangling|  ✅  |
| objdump|  ❌  |
| clang ast view |  ✅  |
| conformance  view |  ✅  |
| graph  view |  ❌  |
| diff  view |  ❌ (although this could be an existing bug)  |
| opt  view |  🚫  |
| theme switching |  ✅  |
| font resizing in editors |  ✅  |
| reset view |  ✅  |
| drag and drop editor panes |  ✅  |
| gcc tree|  🚫   |
| Language switching| ✅ |
| haskell | 🚫   |
| rust | 🚫   |
| swift | 🚫   |
| D | 🚫   |
| pascal | 🚫   |
| sharing | ❌    |
| libraries | 🚫   |
| output pane | ❌    |

**Comment by RabsRincon** [comment]
Image assets 404 locally

**Comment by RabsRincon** [comment]
`Other > Thanks to...` 404s

**Comment by jaredwy** [comment]
The image assets thing is known. I won't be fixing that in this round.

**Comment by jaredwy** [comment]
Going to close this issue @mattgodbolt @RabsRincon what do you think about creating a wiki page with that table above, and start to fill out some "smoke test" steps for all the features listed? So that we have an easy to refer to guide for these large sweeping changes in the future?
